name: test

on: [push, pull_request]

jobs:
    build:
        runs-on: ubuntu-16.04
        strategy:
            matrix:
                deno: [1.1.0]
        name: Deno ${{ matrix.deno }}
        steps:
            - uses: actions/checkout@master
            - name: Setup deno
              uses: denolib/setup-deno@master
              with:
                  deno-version: ${{ matrix.deno }}
            - name: Test
              run: deno test -A --config ./example/tsconfig.json